#!/usr/bin/env python3
"""Generate the AP1 label model from its benchmark data."""

from __future__ import annotations

import argparse
import csv
import os
import re
import shutil
import subprocess
from pathlib import Path


DATASET_ADDRESS = "Test_Dataset/Large-scale-or/AP_testing/AP1/cost_12x12.csv"
EXPECTED_LABEL_OBJECTIVE = "1577.6"
PROBLEM_NAME = "AP1"
GUROBI_CL_ENV_VAR = "GUROBI_CL"


def script_path() -> Path | None:
    try:
        return Path(__file__).resolve()
    except NameError:
        return None


def repo_root() -> Path:
    script = script_path()
    candidates = []
    if script is not None:
        candidates.append(script.parents[2])
    candidates.extend([Path.cwd(), *Path.cwd().parents])

    for candidate in candidates:
        if (candidate / DATASET_ADDRESS).exists():
            return candidate
    return candidates[0]


def default_data_path() -> Path:
    return repo_root() / DATASET_ADDRESS


def default_output_dir() -> Path:
    script = script_path()
    if script is not None:
        return script.parent
    return repo_root() / "label generation code" / "AP"


def read_cost_matrix(csv_path: Path) -> list[list[str]]:
    with csv_path.open(newline="") as handle:
        rows = list(csv.reader(handle))

    if len(rows) < 2:
        raise ValueError(f"{csv_path} does not contain a cost matrix.")

    task_names = rows[0][1:]
    costs: list[list[str]] = []

    for row_number, row in enumerate(rows[1:], start=2):
        if len(row) != len(task_names) + 1:
            raise ValueError(
                f"Row {row_number} has {len(row) - 1} costs, expected {len(task_names)}."
            )
        costs.append(row[1:])

    if len(costs) != len(task_names):
        raise ValueError(
            "AP1 requires a square one-to-one assignment matrix; "
            f"got {len(costs)} rows and {len(task_names)} columns."
        )

    return costs


def wrap_terms(terms: list[str], indent: str = "    ", max_width: int = 90) -> list[str]:
    lines: list[str] = []
    current = indent

    for index, term in enumerate(terms):
        piece = term if index == 0 else f"+ {term}"
        separator = "" if current == indent else " "
        if current != indent and len(current) + len(separator) + len(piece) > max_width:
            lines.append(current)
            current = f"{indent}+ {term}"
        else:
            current = f"{current}{separator}{piece}"

    lines.append(current)
    return lines


def build_label_model(costs: list[list[str]]) -> str:
    n = len(costs)
    lines = [
        r"\Generated by Cardinal Operations",
        "",
        "    Minimize",
    ]

    objective_terms = [f"{costs[i][j]} x_{i}_{j}" for i in range(n) for j in range(n)]
    lines.extend(wrap_terms(objective_terms))
    lines.append("    Subject To")

    row_number = 0
    for i in range(n):
        terms = [f"x_{i}_{j}" for j in range(n)]
        lines.extend(wrap_terms([f"R{row_number}: {terms[0]}", *terms[1:]]))
        lines[-1] = f"{lines[-1]} = 1"
        row_number += 1

    for j in range(n):
        terms = [f"x_{i}_{j}" for i in range(n)]
        lines.extend(wrap_terms([f"R{row_number}: {terms[0]}", *terms[1:]]))
        lines[-1] = f"{lines[-1]} = 1"
        row_number += 1

    lines.append("    END")
    return "\n".join(lines)


def format_objective(value: float) -> str:
    return f"{value:.12g}"


def expected_objective_components() -> tuple[float, int] | None:
    cleaned = EXPECTED_LABEL_OBJECTIVE.replace(",", "")
    match = re.search(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", cleaned)
    if match is None:
        return None
    token = match.group(0)
    mantissa = re.split(r"[eE]", token, maxsplit=1)[0]
    decimals = len(mantissa.split(".", maxsplit=1)[1]) if "." in mantissa else 0
    return float(token), decimals


def objective_matches_expected(objective: str | None) -> bool:
    if objective is None:
        return False
    expected = expected_objective_components()
    if expected is None:
        return False
    expected_value, decimals = expected
    actual = float(objective)
    decimal_tolerance = 0.5 * 10 ** (-decimals) if decimals > 0 else 1e-6
    tolerance = max(1e-6, abs(expected_value) * 1e-9, decimal_tolerance)
    return abs(actual - expected_value) <= tolerance


def parse_gurobi_cli_result(output: str) -> tuple[str, str | None]:
    optimal_match = re.search(r"^Optimal objective\s+([-+0-9.eE]+)", output, re.MULTILINE)
    if optimal_match:
        return "OPTIMAL", format_objective(float(optimal_match.group(1)))

    best_match = re.search(r"^Best objective\s+([-+0-9.eE]+)", output, re.MULTILINE)
    if best_match and re.search(r"^Optimal solution found", output, re.MULTILINE):
        return "OPTIMAL", format_objective(float(best_match.group(1)))

    status_patterns = [
        ("INFEASIBLE", r"^Infeasible model"),
        ("UNBOUNDED", r"^Unbounded model"),
        ("INF_OR_UNBD", r"^Model is infeasible or unbounded"),
        ("TIME_LIMIT", r"^Time limit reached"),
    ]
    for status, pattern in status_patterns:
        if re.search(pattern, output, re.MULTILINE):
            return status, None
    return "UNKNOWN", None


def solve_and_write_mps(lp_path: Path, mps_path: Path) -> tuple[str, str | None]:
    try:
        import gurobipy as gp  # type: ignore[import-not-found]
    except ModuleNotFoundError:
        gurobi_cl = os.environ.get(GUROBI_CL_ENV_VAR) or shutil.which("gurobi_cl")
        if gurobi_cl is None:
            raise RuntimeError(
                "Could not solve/write MPS because neither gurobipy nor gurobi_cl is available. "
                "Install gurobipy in this Python environment, put gurobi_cl on PATH, or set "
                f"{GUROBI_CL_ENV_VAR} to the gurobi_cl executable path."
            )
        env = os.environ.copy()
        env.setdefault("LC_ALL", "C")
        env.setdefault("LANG", "C")
        result = subprocess.run(
            [gurobi_cl, "LogFile=", f"ResultFile={mps_path}", str(lp_path)],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            env=env,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "gurobi_cl failed while solving/writing the MPS file:\n"
                f"{result.stdout}"
            )
        return parse_gurobi_cli_result(result.stdout)

    model = gp.read(str(lp_path))
    model.Params.OutputFlag = 0
    model.optimize()
    model.write(str(mps_path))
    status_name = {
        gp.GRB.OPTIMAL: "OPTIMAL",
        gp.GRB.INFEASIBLE: "INFEASIBLE",
        gp.GRB.UNBOUNDED: "UNBOUNDED",
        gp.GRB.INF_OR_UNBD: "INF_OR_UNBD",
        gp.GRB.TIME_LIMIT: "TIME_LIMIT",
    }.get(model.Status, str(model.Status))
    objective = format_objective(model.ObjVal) if model.SolCount else None
    return status_name, objective


def lp_model_for_files(label_model: str) -> str:
    if "generate_lp_model" in globals():
        return generate_lp_model()
    return label_model


def save_model_files(
    label_model: str,
    output_dir: Path,
    write_mps: bool = True,
) -> tuple[Path, Path | None, tuple[str, str | None] | None]:
    output_dir.mkdir(parents=True, exist_ok=True)
    lp_path = output_dir / f"{PROBLEM_NAME}.lp"
    mps_path = output_dir / f"{PROBLEM_NAME}.mps"
    lp_path.write_text(lp_model_for_files(label_model) + "\n", encoding="utf-8")
    if write_mps:
        solve_result = solve_and_write_mps(lp_path, mps_path)
        return lp_path, mps_path, solve_result
    return lp_path, None, None


def print_generation_summary(
    lp_path: Path,
    mps_path: Path | None,
    solve_result: tuple[str, str | None] | None,
) -> None:
    print()
    print("Gurobi solve result")
    print(f"LP file: {lp_path}")
    if mps_path is None or solve_result is None:
        print("MPS file: skipped")
        print("Status: skipped")
        return

    status, objective = solve_result
    print(f"MPS file: {mps_path}")
    print(f"Status: {status}")
    if objective is not None:
        print(f"Objective: {objective}")
        print(f"Expected objective: {EXPECTED_LABEL_OBJECTIVE}")
        print(f"Matches expected: {objective_matches_expected(objective)}")


def generate_files(
    data_path: Path | None = None,
    output_dir: Path | None = None,
    write_mps: bool = True,
) -> tuple[str, Path, Path | None, tuple[str, str | None] | None]:
    costs = read_cost_matrix(data_path or default_data_path())
    label_model = build_label_model(costs)
    lp_path, mps_path, solve_result = save_model_files(
        label_model,
        output_dir or default_output_dir(),
        write_mps=write_mps,
    )
    return label_model, lp_path, mps_path, solve_result


def print_generation_summary(
    lp_path: Path,
    mps_path: Path | None,
    solve_result: tuple[str, str | None] | None,
) -> None:
    print()
    print("Gurobi solve result")
    print(f"LP file: {lp_path}")
    if mps_path is None or solve_result is None:
        print("MPS file: skipped")
        print("Status: skipped")
        return

    status, objective = solve_result
    print(f"MPS file: {mps_path}")
    print(f"Status: {status}")
    if objective is not None:
        print(f"Objective: {objective}")
        print(f"Expected objective: {EXPECTED_LABEL_OBJECTIVE}")
        print(f"Matches expected: {objective == EXPECTED_LABEL_OBJECTIVE}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the AP1 label model.")
    parser.add_argument(
        "--data",
        type=Path,
        default=default_data_path(),
        help="Path to cost_12x12.csv.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=default_output_dir(),
        help="Directory where AP1.lp and AP1.mps will be written.",
    )
    parser.add_argument(
        "--no-files",
        action="store_true",
        help="Only print the label model; do not write LP or MPS files.",
    )
    parser.add_argument(
        "--skip-mps",
        action="store_true",
        help="Write AP1.lp only; skip AP1.mps generation.",
    )
    parser.add_argument(
        "--write-mps",
        action="store_true",
        help="Deprecated compatibility flag. MPS generation is enabled by default.",
    )
    args, _ = parser.parse_known_args()

    costs = read_cost_matrix(args.data)
    label_model = build_label_model(costs)
    file_result = None
    if not args.no_files:
        file_result = save_model_files(label_model, args.output_dir, write_mps=not args.skip_mps)
    print(label_model)
    if file_result is not None:
        print_generation_summary(*file_result)


if __name__ == "__main__":
    main()
