#!/usr/bin/env python3
"""Generate the UFLP9 label model from its benchmark data."""

from __future__ import annotations

import argparse
import csv
import os
import re
import shutil
import subprocess
from decimal import Decimal
from pathlib import Path


DATASET_ADDRESS = (
    "Test_Dataset/Large-scale-or/UFLP_testing/UFLP9/demand.csv\n"
    "Test_Dataset/Large-scale-or/UFLP_testing/UFLP9/fixed_cost.csv\n"
    "Test_Dataset/Large-scale-or/UFLP_testing/UFLP9/transportation_costs.csv"
)
DEMAND_PATH = "Test_Dataset/Large-scale-or/UFLP_testing/UFLP9/demand.csv"
FIXED_COST_PATH = "Test_Dataset/Large-scale-or/UFLP_testing/UFLP9/fixed_cost.csv"
TRANSPORTATION_COST_PATH = "Test_Dataset/Large-scale-or/UFLP_testing/UFLP9/transportation_costs.csv"
EXPECTED_LABEL_OBJECTIVE = "317318.5"
PROBLEM_NAME = "UFLP9"
GUROBI_CL_ENV_VAR = "GUROBI_CL"


def script_path() -> Path | None:
    try:
        return Path(__file__).resolve()
    except NameError:
        return None


def repo_root() -> Path:
    script = script_path()
    candidates = []
    if script is not None:
        candidates.append(script.parents[2])
    candidates.extend([Path.cwd(), *Path.cwd().parents])

    for candidate in candidates:
        if (candidate / DATASET_ADDRESS.splitlines()[0]).exists():
            return candidate
    return candidates[0]


def default_output_dir() -> Path:
    script = script_path()
    if script is not None:
        return script.parent
    return repo_root() / "label generation code" / "UFLP"


def decimal_sum(values: list[str]) -> str:
    value = sum(Decimal(item) for item in values)
    return format(value, "f")


def is_zero(value: str) -> bool:
    return Decimal(value) == 0


def wrap_terms(terms: list[str], indent: str = "    ", max_width: int = 90) -> list[str]:
    lines: list[str] = []
    current = indent
    for index, term in enumerate(terms):
        piece = term if index == 0 or term.startswith("- ") else f"+ {term}"
        separator = "" if current == indent else " "
        if current != indent and len(current) + len(separator) + len(piece) > max_width:
            lines.append(current)
            current = f"{indent}{piece}"
        else:
            current = f"{current}{separator}{piece}"
    lines.append(current)
    return lines


def wrap_items(items: list[str], indent: str = "    ", max_width: int = 90) -> list[str]:
    lines: list[str] = []
    current = indent
    for item in items:
        separator = "" if current == indent else " "
        if current != indent and len(current) + len(separator) + len(item) > max_width:
            lines.append(current)
            current = f"{indent}{item}"
        else:
            current = f"{current}{separator}{item}"
    lines.append(current)
    return lines


def read_demands(path: Path) -> list[str]:
    with path.open(newline="") as handle:
        return [row["demand"] for row in csv.DictReader(handle)]


def read_fixed_costs(path: Path) -> list[str]:
    with path.open(newline="") as handle:
        return [row["fixed_costs"] for row in csv.DictReader(handle)]


def read_transportation_costs(path: Path) -> list[list[str]]:
    with path.open(newline="") as handle:
        rows = list(csv.reader(handle))
    return [row[1:] for row in rows[1:]]


def build_label_model(
    demands: list[str],
    fixed_costs: list[str],
    transportation_costs: list[list[str]],
) -> str:
    facility_count = len(fixed_costs)
    customer_count = len(demands)
    big_m = decimal_sum(demands)

    lines = [r"\Generated by Cardinal Operations", "", "    Minimize"]
    objective_terms = [
        f"{transportation_costs[i][j]} x_{i}_{j}"
        for i in range(facility_count)
        for j in range(customer_count)
        if not is_zero(transportation_costs[i][j])
    ]
    objective_terms.extend(f"{fixed_costs[i]} y_{i}" for i in range(facility_count))
    lines.extend(wrap_terms(objective_terms))
    lines.append("    Subject To")

    row_number = 0
    for j in range(customer_count):
        terms = [f"x_{i}_{j}" for i in range(facility_count)]
        lines.extend(wrap_terms([f"R{row_number}: {terms[0]}", *terms[1:]]))
        lines[-1] = f"{lines[-1]} = {demands[j]}"
        row_number += 1

    for i in range(facility_count):
        terms = [f"x_{i}_{j}" for j in range(customer_count)]
        terms.append(f"- {big_m} y_{i}")
        lines.extend(wrap_terms([f"R{row_number}: {terms[0]}", *terms[1:]]))
        lines[-1] = f"{lines[-1]} <= 0"
        row_number += 1

    lines.append("    Binaries")
    lines.extend(wrap_items([f"y_{i}" for i in range(facility_count)]))
    lines.append("    END")
    return "\n".join(lines)



def generate_label_model() -> str:
    root = repo_root()
    return build_label_model(
        read_demands(root / DEMAND_PATH),
        read_fixed_costs(root / FIXED_COST_PATH),
        read_transportation_costs(root / TRANSPORTATION_COST_PATH),
    )


def format_objective(value: float) -> str:
    return f"{value:.12g}"


def expected_objective_components() -> tuple[float, int] | None:
    cleaned = EXPECTED_LABEL_OBJECTIVE.replace(",", "")
    match = re.search(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", cleaned)
    if match is None:
        return None
    token = match.group(0)
    mantissa = re.split(r"[eE]", token, maxsplit=1)[0]
    decimals = len(mantissa.split(".", maxsplit=1)[1]) if "." in mantissa else 0
    return float(token), decimals


def objective_matches_expected(objective: str | None) -> bool:
    if objective is None:
        return False
    expected = expected_objective_components()
    if expected is None:
        return False
    expected_value, decimals = expected
    actual = float(objective)
    decimal_tolerance = 0.5 * 10 ** (-decimals) if decimals > 0 else 1e-6
    tolerance = max(1e-6, abs(expected_value) * 1e-9, decimal_tolerance)
    return abs(actual - expected_value) <= tolerance


def parse_gurobi_cli_result(output: str) -> tuple[str, str | None]:
    optimal_match = re.search(r"^Optimal objective\s+([-+0-9.eE]+)", output, re.MULTILINE)
    if optimal_match:
        return "OPTIMAL", format_objective(float(optimal_match.group(1)))

    best_match = re.search(r"^Best objective\s+([-+0-9.eE]+)", output, re.MULTILINE)
    if best_match and re.search(r"^Optimal solution found", output, re.MULTILINE):
        return "OPTIMAL", format_objective(float(best_match.group(1)))

    status_patterns = [
        ("INFEASIBLE", r"^Infeasible model"),
        ("UNBOUNDED", r"^Unbounded model"),
        ("INF_OR_UNBD", r"^Model is infeasible or unbounded"),
        ("TIME_LIMIT", r"^Time limit reached"),
    ]
    for status, pattern in status_patterns:
        if re.search(pattern, output, re.MULTILINE):
            return status, None
    return "UNKNOWN", None


def solve_and_write_mps(lp_path: Path, mps_path: Path) -> tuple[str, str | None]:
    try:
        import gurobipy as gp  # type: ignore[import-not-found]
    except ModuleNotFoundError:
        gurobi_cl = os.environ.get(GUROBI_CL_ENV_VAR) or shutil.which("gurobi_cl")
        if gurobi_cl is None:
            raise RuntimeError(
                "Could not solve/write MPS because neither gurobipy nor gurobi_cl is available. "
                "Install gurobipy in this Python environment, put gurobi_cl on PATH, or set "
                f"{GUROBI_CL_ENV_VAR} to the gurobi_cl executable path."
            )
        env = os.environ.copy()
        env.setdefault("LC_ALL", "C")
        env.setdefault("LANG", "C")
        result = subprocess.run(
            [gurobi_cl, "LogFile=", f"ResultFile={mps_path}", str(lp_path)],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            env=env,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "gurobi_cl failed while solving/writing the MPS file:\n"
                f"{result.stdout}"
            )
        return parse_gurobi_cli_result(result.stdout)

    model = gp.read(str(lp_path))
    model.Params.OutputFlag = 0
    model.optimize()
    model.write(str(mps_path))
    status_name = {
        gp.GRB.OPTIMAL: "OPTIMAL",
        gp.GRB.INFEASIBLE: "INFEASIBLE",
        gp.GRB.UNBOUNDED: "UNBOUNDED",
        gp.GRB.INF_OR_UNBD: "INF_OR_UNBD",
        gp.GRB.TIME_LIMIT: "TIME_LIMIT",
    }.get(model.Status, str(model.Status))
    objective = format_objective(model.ObjVal) if model.SolCount else None
    return status_name, objective


def lp_model_for_files(label_model: str) -> str:
    if "generate_lp_model" in globals():
        return generate_lp_model()
    return label_model


def save_model_files(
    label_model: str,
    output_dir: Path,
    write_mps: bool = True,
) -> tuple[Path, Path | None, tuple[str, str | None] | None]:
    output_dir.mkdir(parents=True, exist_ok=True)
    lp_path = output_dir / f"{PROBLEM_NAME}.lp"
    mps_path = output_dir / f"{PROBLEM_NAME}.mps"
    lp_path.write_text(lp_model_for_files(label_model) + "\n", encoding="utf-8")
    if write_mps:
        solve_result = solve_and_write_mps(lp_path, mps_path)
        return lp_path, mps_path, solve_result
    return lp_path, None, None


def print_generation_summary(
    lp_path: Path,
    mps_path: Path | None,
    solve_result: tuple[str, str | None] | None,
) -> None:
    print()
    print("Gurobi solve result")
    print(f"LP file: {lp_path}")
    if mps_path is None or solve_result is None:
        print("MPS file: skipped")
        print("Status: skipped")
        return

    status, objective = solve_result
    print(f"MPS file: {mps_path}")
    print(f"Status: {status}")
    if objective is not None:
        print(f"Objective: {objective}")
        print(f"Expected objective: {EXPECTED_LABEL_OBJECTIVE}")
        print(f"Matches expected: {objective_matches_expected(objective)}")


def generate_files(
    output_dir: Path | None = None,
    write_mps: bool = True,
) -> tuple[str, Path, Path | None, tuple[str, str | None] | None]:
    label_model = generate_label_model()
    lp_path, mps_path, solve_result = save_model_files(
        label_model,
        output_dir or default_output_dir(),
        write_mps=write_mps,
    )
    return label_model, lp_path, mps_path, solve_result


def main() -> None:
    parser = argparse.ArgumentParser(description=f"Generate the {PROBLEM_NAME} label model.")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=default_output_dir(),
        help=f"Directory where {PROBLEM_NAME}.lp and {PROBLEM_NAME}.mps will be written.",
    )
    parser.add_argument(
        "--no-files",
        action="store_true",
        help="Only print the label model; do not write LP or MPS files.",
    )
    parser.add_argument(
        "--skip-mps",
        action="store_true",
        help=f"Write {PROBLEM_NAME}.lp only; skip {PROBLEM_NAME}.mps generation.",
    )
    args, _ = parser.parse_known_args()

    label_model = generate_label_model()
    if not args.no_files:
        save_model_files(label_model, args.output_dir, write_mps=not args.skip_mps)
    print(label_model)


if __name__ == "__main__":
    main()
