#!/usr/bin/env python3
"""Generate the UFLP14 label model from its benchmark data."""

from __future__ import annotations

import argparse
import csv
import os
import re
import shutil
import subprocess
from decimal import Decimal
from pathlib import Path


def script_path() -> Path | None:
    try:
        return Path(__file__).resolve()
    except NameError:
        return None


def repo_root() -> Path:
    script = script_path()
    candidates = []
    if script is not None:
        candidates.append(script.parents[2])
    candidates.extend([Path.cwd(), *Path.cwd().parents])

    for candidate in candidates:
        if (candidate / DATASET_ADDRESS.splitlines()[0]).exists():
            return candidate
    return candidates[0]


def default_output_dir() -> Path:
    script = script_path()
    if script is not None:
        return script.parent
    return repo_root() / "label generation code" / "UFLP"


def is_zero(value: str) -> bool:
    return Decimal(value) == 0


def wrap_terms(terms: list[str], indent: str = "    ", max_width: int = 90) -> list[str]:
    lines: list[str] = []
    current = indent
    for index, term in enumerate(terms):
        piece = term if index == 0 or term.startswith("- ") else f"+ {term}"
        separator = "" if current == indent else " "
        if current != indent and len(current) + len(separator) + len(piece) > max_width:
            lines.append(current)
            current = f"{indent}{piece}"
        else:
            current = f"{current}{separator}{piece}"
    lines.append(current)
    return lines


def wrap_items(items: list[str], indent: str = "    ", max_width: int = 90) -> list[str]:
    lines: list[str] = []
    current = indent
    for item in items:
        separator = "" if current == indent else " "
        if current != indent and len(current) + len(separator) + len(item) > max_width:
            lines.append(current)
            current = f"{indent}{item}"
        else:
            current = f"{current}{separator}{item}"
    lines.append(current)
    return lines


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def read_matrix(path: Path) -> tuple[list[str], list[str], list[list[str]]]:
    with path.open(newline="") as handle:
        rows = list(csv.reader(handle))
    row_names = [row[0] for row in rows[1:]]
    column_names = rows[0][1:]
    values = [row[1:] for row in rows[1:]]
    return row_names, column_names, values


def build_continuous_facility_location_model(
    facility_names: list[str],
    customer_names: list[str],
    demands: list[str],
    fixed_costs: list[str],
    service_costs: list[list[str]],
    capacities: list[str],
    x_name,
    y_name,
) -> str:
    lines = [r"\Generated by Cardinal Operations", "", "    Minimize"]

    objective_terms: list[str] = []
    for i, fixed_cost in enumerate(fixed_costs):
        if not is_zero(fixed_cost):
            objective_terms.append(f"{fixed_cost} {y_name(i)}")
    for i in range(len(facility_names)):
        for j in range(len(customer_names)):
            cost = service_costs[i][j]
            if not is_zero(cost):
                objective_terms.append(f"{cost} {x_name(i, j)}")

    lines.extend(wrap_terms(objective_terms))
    lines.append("    Subject To")

    for j, customer_name in enumerate(customer_names):
        terms = [x_name(i, j) for i in range(len(facility_names))]
        lines.extend(wrap_terms([f"Demand_{customer_name}: {terms[0]}", *terms[1:]]))
        lines[-1] = f"{lines[-1]} = {demands[j]}"

    for i, facility_name in enumerate(facility_names):
        terms = [x_name(i, j) for j in range(len(customer_names))]
        terms.append(f"- {capacities[i]} {y_name(i)}")
        lines.extend(wrap_terms([f"Capacity_{facility_name}: {terms[0]}", *terms[1:]]))
        lines[-1] = f"{lines[-1]} <= 0"

    lines.append("    Binaries")
    lines.extend(wrap_items([y_name(i) for i in range(len(facility_names))]))
    lines.append("    END")
    return "\n".join(lines)


DATASET_ADDRESS = (
    "Test_Dataset/Large-scale-or/UFLP_testing/UFLP14/PotentialWarehouses_Costs.csv\n"
    "Test_Dataset/Large-scale-or/UFLP_testing/UFLP14/Stores_Demands.csv\n"
    "Test_Dataset/Large-scale-or/UFLP_testing/UFLP14/TransportationCost.csv"
)
WAREHOUSE_PATH = "Test_Dataset/Large-scale-or/UFLP_testing/UFLP14/PotentialWarehouses_Costs.csv"
DEMAND_PATH = "Test_Dataset/Large-scale-or/UFLP_testing/UFLP14/Stores_Demands.csv"
TRANSPORTATION_COST_PATH = "Test_Dataset/Large-scale-or/UFLP_testing/UFLP14/TransportationCost.csv"
EXPECTED_LABEL_OBJECTIVE = "10188"
PROBLEM_NAME = "UFLP14"
GUROBI_CL_ENV_VAR = "GUROBI_CL"


def build_label_model() -> str:
    root = repo_root()
    warehouses = read_rows(root / WAREHOUSE_PATH)
    stores = read_rows(root / DEMAND_PATH)
    _, _, store_by_warehouse_costs = read_matrix(root / TRANSPORTATION_COST_PATH)
    facility_names = [f"W{row['Warehouse (i)']}" for row in warehouses]
    customer_names = [f"S{row['Store (j)']}" for row in stores]
    costs = [
        [store_by_warehouse_costs[j][i] for j in range(len(customer_names))]
        for i in range(len(facility_names))
    ]
    return build_continuous_facility_location_model(
        facility_names,
        customer_names,
        [row["Demand (units, dj)"] for row in stores],
        [row["Opening Cost (fi)"] for row in warehouses],
        costs,
        [row["Capacity (units)"] for row in warehouses],
        x_name=lambda i, j: f"x_{facility_names[i]}_{customer_names[j]}",
        y_name=lambda i: f"y_{facility_names[i]}",
    )



def generate_label_model() -> str:
    return build_label_model()


def format_objective(value: float) -> str:
    return f"{value:.12g}"


def expected_objective_components() -> tuple[float, int] | None:
    cleaned = EXPECTED_LABEL_OBJECTIVE.replace(",", "")
    match = re.search(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", cleaned)
    if match is None:
        return None
    token = match.group(0)
    mantissa = re.split(r"[eE]", token, maxsplit=1)[0]
    decimals = len(mantissa.split(".", maxsplit=1)[1]) if "." in mantissa else 0
    return float(token), decimals


def objective_matches_expected(objective: str | None) -> bool:
    if objective is None:
        return False
    expected = expected_objective_components()
    if expected is None:
        return False
    expected_value, decimals = expected
    actual = float(objective)
    decimal_tolerance = 0.5 * 10 ** (-decimals) if decimals > 0 else 1e-6
    tolerance = max(1e-6, abs(expected_value) * 1e-9, decimal_tolerance)
    return abs(actual - expected_value) <= tolerance


def parse_gurobi_cli_result(output: str) -> tuple[str, str | None]:
    optimal_match = re.search(r"^Optimal objective\s+([-+0-9.eE]+)", output, re.MULTILINE)
    if optimal_match:
        return "OPTIMAL", format_objective(float(optimal_match.group(1)))

    best_match = re.search(r"^Best objective\s+([-+0-9.eE]+)", output, re.MULTILINE)
    if best_match and re.search(r"^Optimal solution found", output, re.MULTILINE):
        return "OPTIMAL", format_objective(float(best_match.group(1)))

    status_patterns = [
        ("INFEASIBLE", r"^Infeasible model"),
        ("UNBOUNDED", r"^Unbounded model"),
        ("INF_OR_UNBD", r"^Model is infeasible or unbounded"),
        ("TIME_LIMIT", r"^Time limit reached"),
    ]
    for status, pattern in status_patterns:
        if re.search(pattern, output, re.MULTILINE):
            return status, None
    return "UNKNOWN", None


def solve_and_write_mps(lp_path: Path, mps_path: Path) -> tuple[str, str | None]:
    try:
        import gurobipy as gp  # type: ignore[import-not-found]
    except ModuleNotFoundError:
        gurobi_cl = os.environ.get(GUROBI_CL_ENV_VAR) or shutil.which("gurobi_cl")
        if gurobi_cl is None:
            raise RuntimeError(
                "Could not solve/write MPS because neither gurobipy nor gurobi_cl is available. "
                "Install gurobipy in this Python environment, put gurobi_cl on PATH, or set "
                f"{GUROBI_CL_ENV_VAR} to the gurobi_cl executable path."
            )
        env = os.environ.copy()
        env.setdefault("LC_ALL", "C")
        env.setdefault("LANG", "C")
        result = subprocess.run(
            [gurobi_cl, "LogFile=", f"ResultFile={mps_path}", str(lp_path)],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            env=env,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "gurobi_cl failed while solving/writing the MPS file:\n"
                f"{result.stdout}"
            )
        return parse_gurobi_cli_result(result.stdout)

    model = gp.read(str(lp_path))
    model.Params.OutputFlag = 0
    model.optimize()
    model.write(str(mps_path))
    status_name = {
        gp.GRB.OPTIMAL: "OPTIMAL",
        gp.GRB.INFEASIBLE: "INFEASIBLE",
        gp.GRB.UNBOUNDED: "UNBOUNDED",
        gp.GRB.INF_OR_UNBD: "INF_OR_UNBD",
        gp.GRB.TIME_LIMIT: "TIME_LIMIT",
    }.get(model.Status, str(model.Status))
    objective = format_objective(model.ObjVal) if model.SolCount else None
    return status_name, objective


def lp_model_for_files(label_model: str) -> str:
    if "generate_lp_model" in globals():
        return generate_lp_model()
    return label_model


def save_model_files(
    label_model: str,
    output_dir: Path,
    write_mps: bool = True,
) -> tuple[Path, Path | None, tuple[str, str | None] | None]:
    output_dir.mkdir(parents=True, exist_ok=True)
    lp_path = output_dir / f"{PROBLEM_NAME}.lp"
    mps_path = output_dir / f"{PROBLEM_NAME}.mps"
    lp_path.write_text(lp_model_for_files(label_model) + "\n", encoding="utf-8")
    if write_mps:
        solve_result = solve_and_write_mps(lp_path, mps_path)
        return lp_path, mps_path, solve_result
    return lp_path, None, None


def print_generation_summary(
    lp_path: Path,
    mps_path: Path | None,
    solve_result: tuple[str, str | None] | None,
) -> None:
    print()
    print("Gurobi solve result")
    print(f"LP file: {lp_path}")
    if mps_path is None or solve_result is None:
        print("MPS file: skipped")
        print("Status: skipped")
        return

    status, objective = solve_result
    print(f"MPS file: {mps_path}")
    print(f"Status: {status}")
    if objective is not None:
        print(f"Objective: {objective}")
        print(f"Expected objective: {EXPECTED_LABEL_OBJECTIVE}")
        print(f"Matches expected: {objective_matches_expected(objective)}")


def generate_files(
    output_dir: Path | None = None,
    write_mps: bool = True,
) -> tuple[str, Path, Path | None, tuple[str, str | None] | None]:
    label_model = generate_label_model()
    lp_path, mps_path, solve_result = save_model_files(
        label_model,
        output_dir or default_output_dir(),
        write_mps=write_mps,
    )
    return label_model, lp_path, mps_path, solve_result


def main() -> None:
    parser = argparse.ArgumentParser(description=f"Generate the {PROBLEM_NAME} label model.")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=default_output_dir(),
        help=f"Directory where {PROBLEM_NAME}.lp and {PROBLEM_NAME}.mps will be written.",
    )
    parser.add_argument(
        "--no-files",
        action="store_true",
        help="Only print the label model; do not write LP or MPS files.",
    )
    parser.add_argument(
        "--skip-mps",
        action="store_true",
        help=f"Write {PROBLEM_NAME}.lp only; skip {PROBLEM_NAME}.mps generation.",
    )
    args, _ = parser.parse_known_args()

    label_model = generate_label_model()
    if not args.no_files:
        save_model_files(label_model, args.output_dir, write_mps=not args.skip_mps)
    print(label_model)


if __name__ == "__main__":
    main()
